# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: todo_no_pose_selected
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - Base
    - 1stick
    - 2stick
    - 3to4
    - GrabR
    - Grabl
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
controler:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Base
    - 1stick
    - 2stick
    - 3to4
  gains:
    Base:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    1stick:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    2stick:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    3to4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1